# Generated by Django 4.2.1 on 2024-03-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_alter_movie_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="crt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="actor",
            name="upd",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
        migrations.AlterField(
            model_name="director",
            name="crt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="director",
            name="upd",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="crt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="upd",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="crt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="upd",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
    ]
