# Generated by Django 4.2.1 on 2024-03-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_alter_actor_crt_alter_actor_upd_alter_director_crt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
